---
RecipeFormatVersion: "2020-01-25"
ComponentName: "{COMPONENT_NAME}"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription: "Demonstrates how to query the robot state service, publish current robot state, and publish robot metrics."
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentConfiguration:
  DefaultConfiguration:
    accessControl:
      aws.greengrass.ipc.mqttproxy:
        "$component_name:pub:1":
          policyDescription: Allows access to publish to IoT Core topic(s).
          operations:
            - "aws.greengrass#PublishToIoTCore"
          resources:
            - "*"
Manifests:
  - Platform:
      os: linux
    Lifecycle:
      Run:
        Setenv:
          PYTHONPATH: "{artifacts:decompressedPath}/aws.samples.spot_robot_demo.PublishRobotState"
        Script: |
          python3 -u {artifacts:decompressedPath}/aws.samples.spot_robot_demo.PublishRobotState/app.py
    Artifacts:
      - URI: "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/aws.samples.spot_robot_demo.PublishRobotState.zip"
        Unarchive: ZIP
