version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - apt-get update -y
      - python -m pip install -U pip
      - pip install boto3 --upgrade
      - pip install -r ./artifacts/requirements.txt -t ./artifacts
    finally:
      - echo Exiting the install phase.
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - aws s3 cp $BUILD_SCRIPT_URL build_component_version.py
      - python build_component_version.py -c $COMPONENT_NAME -p $S3_PATH
    finally:
      - echo Exiting the build phase.
