---
RecipeFormatVersion: "2020-01-25"
ComponentName: "{COMPONENT_NAME}"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription: "Demonstrates how to perform S3 uploads with Spot docking callback with Greengrass-provided credentials."
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentDependencies:
  aws.greengrass.TokenExchangeService:
    VersionRequirement: "^2.0.0"
    DependencyType: HARD
Manifests:
  - Platform:
      os: linux
    Artifacts:
      - URI: "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/aws.samples.spot_robot_demo.UploadAction.zip"
        Unarchive: ZIP
    Lifecycle:
      Run:
        Setenv:
          PYTHONPATH: "{artifacts:decompressedPath}/aws.samples.spot_robot_demo.UploadAction"
          S3_BUCKET: greengrass-v2-spot-robot-demo-us-west-2
        Script: |
          python3 -u {artifacts:decompressedPath}/aws.samples.spot_robot_demo.UploadAction/app.py --host-ip 192.168.50.5 --port 50077 --bucket-name $S3_BUCKET --unzip 192.168.50.3
